name: My Ascii Workflow

on: push

jobs:
  basic-detail:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Execute Script
          run : |
            chmod +x shellscript.sh
            ./shellscript.sh
    