name: My Ascii Workflow

on: push

env:
  NAME: "ANSHUL"
  AGE: "16"

jobs:
  build-phase:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Install cowsay
          run: sudo apt-get install cowsay -y
        
        - name: createFile
          run: cowsay -f dragon "Run for cover, I feel a sneeze coming on. cc- dragon" >> dragon.txt

        - name: uploadFile
          uses: actions/upload-artifact@v4
          with:
            name: dragonfile
            path: dragon.txt
            
        - name: printenv
          run: |
            echo hello $NAME $AGE
        # - name: Execute Script
        #   run : |
        #     chmod +x shellscript.sh
        #     ./shellscript.sh

  test-phase:
    needs: [build-phase]
    runs-on: ubuntu-latest
    steps:
        # - name: Checkout Repo
        #   uses: actions/checkout@v4

        - name: downloadFile
          uses: actions/download-artifact@v4
          with:
            name: dragonfile

        - name: Test file
          run: grep -i "dragon" dragon.txt
        
        
  deploy-phase:
    needs: [build-phase,test-phase]
    runs-on: ubuntu-latest
    steps:
        # - name: Checkout Repo
        #   uses: actions/checkout@v4
        - name: downloadFile
          uses: actions/download-artifact@v4
          with:
            name: dragonfile
        
        - run: ls -ltra

        - name: Deploy
          run: |
            cat dragon.txt
            ls -ltra
        
       