name: My First Workflow

on: push

jobs:
  basic-detail:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: List Directory
          run: |
            echo "hello World!"
            ls -ltra
            cat README.md

 
        
        - name: print dragon
          run : cowsay -f dragon "Run for cover, I feel a sneeze coming on."
        
        # - name: Readme.md
        #   run: cat README.md
        
        # - name: Hello Message
        #   run: echo "hello World!"

    