name: My First Workflow

on: push

jobs:
  basic-detail:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: List Directory
          run: ls
        
        - name: Readme.md
          run: cat README.md
        
        - name: Hello Message
          run: echo "hello World!"

    